TARGET	= libmatmult.so
LIBSRCS	= matmult_all.c matmult_blk.c matmult_lib.c
LIBOBJS	= matmult_all.o matmult_blk.o matmult_lib.o

OPT	= -g -O3
PIC	= -fPIC

CC	= gcc
CFLAGS= $(OPT) $(PIC) $(XOPTS)

SOFLAGS = -shared 
XLIBS	= 

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS) 
